//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PathToJannah.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Admin
    {
        public int AID { get; set; }
        public string Name { get; set; }

        
        [DataType(DataType.EmailAddress)]
        [System.ComponentModel.DisplayName("Email")]
        [Required(ErrorMessage = "Email is Required")]
        public string email { get; set; }

        [DataType(DataType.Password)]
        [System.ComponentModel.DisplayName("Password")]
        [Required(ErrorMessage = "Password is Required")]
        public string pass { get; set; }

    
        public string LoginErrorMessage { get; set; }
    }
}
