//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PathToJannah.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Allah_name
    {
        public int A_ID { get; set; }
        public string Name { get; set; }
        public string Meaning { get; set; }
    }
}
