//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PathToJannah.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int C_ID { get; set; }
        public string Comment1 { get; set; }
        public Nullable<System.DateTime> C_Date { get; set; }
        public Nullable<int> U_ID { get; set; }
        public Nullable<int> P_ID { get; set; }
    
        public virtual Blog Blog { get; set; }
        public virtual User User { get; set; }
    }
}
