//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PathToJannah.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comments
    {
        public int C_ID { get; set; }
        public string Comment { get; set; }
        public System.DateTime C_Date { get; set; }
        public int U_ID { get; set; }
        public int P_ID { get; set; }
    }
}
