//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PathToJannah.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Donation
    {
        public int D_ID { get; set; }
        [Required]
        [DataType(DataType.Currency)]
        public string Amount { get; set; }
        [Required]
        [DisplayName("Transaction Id")]
        public string T_ID { get; set; }
        [DataType(DataType.Date)]
        [Required]
        [DisplayName("Transaction Date")]
        public string t_time { get; set; }
        public int U_ID { get; set; }
    }
}
