//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PathToJannah.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donation
    {
        public int D_ID { get; set; }
        public string Amount { get; set; }
        public string T_ID { get; set; }
        public string t_time { get; set; }
        public Nullable<int> U_ID { get; set; }
    
        public virtual User User { get; set; }
    }
}
