//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PathToJannah.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dua
    {
        public int DU_ID { get; set; }
        public string Name { get; set; }
        public string Dua_txt { get; set; }
        public string Dua_meaning { get; set; }
        public Nullable<int> U_ID { get; set; }
    
        public virtual User User { get; set; }
    }
}
