//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PathToJannah.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PTJEntities : DbContext
    {
        public PTJEntities()
            : base("name=PTJEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Blog> Blogs { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<Donation> Donations { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Allah_name> Allah_name { get; set; }
        public virtual DbSet<Dua> Duas { get; set; }
        public virtual DbSet<Hadith> Hadiths { get; set; }
        public virtual DbSet<Surah> Surahs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
