//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PathToJannah.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Surah
    {
        public int S_ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Ayat { get; set; }
        public string Origin { get; set; }
        public string Surah_txt { get; set; }
        public Nullable<int> U_ID { get; set; }
        public string Surah_meaning { get; set; }
    
        public virtual User User { get; set; }
    }
}
